### PR TITLE
Make scripts pass with Standard JS code style 16.0.1

### PR DESCRIPTION
**Pull request by d-r-q**

### CODE REVIEW

**Comment by jiri-janousek** [comment]
Hello @d-r-q, could you push your branch directly to https://github.com/tiliado/nuvola-app-yandex-music (branch `standardjs`)? You should have commit access to that repository. If not, let me know.

**Comment by d-r-q** [comment]
Ok, I will commit it tomorrow

**Comment by d-r-q** [comment]
@fenryxo 
done: https://github.com/tiliado/nuvola-app-yandex-music/tree/standardjs

**Comment by jiri-janousek** [comment]
Ok, please create a pull request from that branch :+1:

**Pull request closed without merging**
